config/routes.rb
Rails.application.routes.draw do
  root to: 'sequences#index'

  get 'sign_up', to: 'users#new', as: 'sign_up'
  get 'log_in', to: 'sessions#new', as: 'log_in'
  get 'log_out', to: 'sessions#destroy', as: 'log_out'
  get '/auth/github/callback' => 'sessions#create_with_github'
  post '/sequences/:id', to: 'sequences#update'
  patch '/sequences/:sequence_id/poses/:id', to: 'sequences#update'
  patch '/sequences/:sequence_id/poses', to: 'sequences#add_pose', as: 'sequence_add_pose'
  get '/sequences/:sequence_id/pose/:id', to: 'poses#list'

  resources :sequences do
    resources :poses, only: [:index, :new]
    resources :comments, only: [:create]
  end

  resources :users, only: [:create]
  resources :sessions, only: [:create]

end

app/controllers/poses_controller.rb
class PosesController < ApplicationController
  before_action :find_sequence
  before_action :set_poses

  def list
    @pose = Pose.find(params[:id])
    render plain: @pose
  end

  def index
    #editing a pose moves that pose to end of @sequence.poses
  end

  def show

  end

  def new
    @sequence = Sequence.find(params[:sequence_id])
    @sequence2 = Sequence.new
    @pose = @sequence2.poses.build
  end

  def create
  end

  def update
  end

private

  def find_sequence
    @sequence = Sequence.find(params[:sequence_id])
  end

  def set_poses
    @poses = Pose.all
  end
end

app/helpers/poses_helper.rb
module PosesHelper
end

app/views/poses/index.html.erb
<div class="sequenceInfo">
  <div id="sequenceTitle"></div>
  <div id="nextSequence"><a href="#" class="js-next" data-id="">Next Sequence</a></div>
  <div id="sequence-difficulty"></div>
</div>

<div id="pose_sequence" style="text-align: center">
  <div id="repititions"></div>
  <div id="poses"></div>
</div>

<div class="addEditPoses">
  <div class="newPose">
    <%= link_to "Add a new pose", new_sequence_pose_path(@sequence), class: 'linkText' %>
  </div>
  <div class="editPost">
    <%= link_to "Edit poses", edit_sequence_path(@sequence), class: 'linkText' %>
  </div>
</div>

<div class="comments">
  <div id="commentForm">
    <%= form_for ([@sequence, @sequence.comments.build]), html: {:class => 'comment_form'} do |f| %>
      <%= f.label :content, "Leave a commment" %><br /><br />
      <%= f.text_area :content, class: 'comment_form' %><br />
      <%= f.submit %>
    <% end %>
  </div>
  <div id="display_comments"></div>
</div>

app/views/poses/new.html.erb
<div class="addPose">
  <%= render 'layouts/add_new_sequence_poses' %>
</div>

app/views/poses/show.html.erb
<div class="sequenceDescription">
  <h2>For <%= @sequence.repititions %> rounds, repeat the following sequence of poses: </h2>
    <div id="poseList">
      <% @sequence.poses.each.with_index do |pose, i| %>
      <h3 class="poseListing">
        <%= i + 1 %>. <%= pose.name %> - <%= pose.description %>
      </h3>
      <% end %>
    </div>
</div>