config/routes.rb
Rails.application.routes.draw do
  root to: 'sequences#index'

  get 'sign_up', to: 'users#new', as: 'sign_up'
  get 'log_in', to: 'sessions#new', as: 'log_in'
  get 'log_out', to: 'sessions#destroy', as: 'log_out'
  get '/auth/github/callback' => 'sessions#create_with_github'
  post '/sequences/:id', to: 'sequences#update'
  patch '/sequences/:sequence_id/poses/:id', to: 'sequences#update'
  patch '/sequences/:sequence_id/poses', to: 'sequences#add_pose', as: 'sequence_add_pose'
  get '/sequences/:sequence_id/pose/:id', to: 'poses#list'

  resources :sequences do
    resources :poses, only: [:index, :new]
    resources :comments, only: [:create]
  end

  resources :users, only: [:create]
  resources :sessions, only: [:create]

end

app/views/layouts/_add_new_sequence_poses.html.erb
<div class="new-sequence">
  <%= form_for @sequence, url: sequence_poses_path(@sequence) do |f| %>
    <%= f.fields_for @pose do |pose_builder| %>
        <%= f.label :add_pose_to_this_sequence %>
        <%= select_tag 'sequence[pose_ids][]', options_from_collection_for_select(@poses.sort_by {|pose| pose.name}, "id", "name"), { :prompt => 'Select a pose'} %>
        or create a new pose:
        <%= pose_builder.label :name %>
        <%= pose_builder.text_field :name %>
        <%= pose_builder.label :description %>
        <%= pose_builder.text_field :description %><br />
    <% end %>
    <%= f.submit 'update' %>
  <% end %>
</div>

app/views/layouts/_add_poses_to_sequence_form.html.erb
<%= form_for(@sequence) do |f| %>
  <%= f.fields_for :poses do |pose_builder| %>
      Edit pose:
      <%= pose_builder.label :name %>
      <%= pose_builder.text_field :name%>
      <%= pose_builder.label :description %>
      <%= pose_builder.text_field :description %><br />
  <% end %>
  <%= f.label :repititions %>
  <%= f.select :repititions, options_for_select(1..10), :prompt => 'Select number of repitions' %>
  <%= f.submit %>
<% end %>

app/views/layouts/_chakras.html.erb
<div class="chakras">
  <div id="chakraIcons">
    <div class="row">
      <div class="col-lg-12">
        <%= image_tag('chakras/6th-chakra.png', :class => "chakraIcon", :id => "purple")  %>
      </div>
      <div class="col-lg-12">
        <%= image_tag('chakras/5th-chakra.png', :class => "chakraIcon", :id => "blue")  %>
      </div>
      <div class="col-lg-12">
        <%= image_tag('chakras/4th-chakra.png', :class => "chakraIcon", :id => "green")  %>
      </div>
      <div class="col-lg-12">
        <%= image_tag('chakras/3rd-chakra.png', :class => "chakraIcon", :id => "yellow")  %>
      </div>
      <div class="col-lg-12">
        <%= image_tag('chakras/2nd-chakra.png', :class => "chakraIcon", :id => "orange")  %>
      </div>
      <div class="col-lg-12">
        <%= image_tag('chakras/1st-chakra.png', :class => "chakraIcon", :id => "red")  %>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_edit_sequence_poses.html.erb
<div class="edit-sequence">
  <%= form_for(@sequence) do |f| %>
    <%= f.fields_for :poses do |pose_builder| %>
        Edit pose:
        <%= pose_builder.label :name %>
        <%= pose_builder.text_field :name%>
        <%= pose_builder.label :description %>
        <%= pose_builder.text_field :description %><br />
    <% end %>
    <%= f.label :repititions %>
    <%= f.select :repititions, options_for_select(1..10), :prompt => 'Select number of repitions' %>
    <%= f.submit %>
  <% end %>
</div>

app/views/layouts/_form_errors.html.erb
<div class="form_errors">
  <% content_for :form_errors do %>
    <% if !object.errors.empty? %>
      <p>
        <%= pluralize(object.errors.count, "error") %> prevented the form from being saved:
      </p>

      <ul>
        <% object.errors.full_messages.each do |message| %>
        <li><%= message %></li>
        <% end %>
      </ul>
    <% end %>
  <% end %>
</div>

app/views/layouts/_guest_header.html.erb
<%= link_to "Sign Up", sign_up_path %> |
<%= link_to "Log In", log_in_path %>

app/views/layouts/_guest_sub_header.html.erb
<div class="linText guest_sub_header row">
  <div class="col-lg-4">
    <div id="log-in">
      <h4><%= link_to "Log In", log_in_path %></h4>
    </div>
  </div>

  <div class="col-lg-4">
    <div id="signUp">
      <h4><%= link_to "Sign Up", sign_up_path %></h4>
    </div>
  </div>

  <div class="col-lg-4">
    <div id="git-log-in">
      <h4><%= link_to "Log in with GitHub", "/auth/github" %></h4>
    </div>
  </div>
</div>

app/views/layouts/_header.html.erb
<div class="headerText">
  <div class="welcomeText">
      <h1>Welcome to YogaFlow
        <% if current_user %>
            <%= current_user.username %>!</h1>
          <% else %>
            "Future Yogi!"
          <% end %>
  </div>
</div>


<div id="userHeader" align="center">
  <% if current_user %>
    <%= render '/layouts/user_sub_header' %>
  <% else %>
    <%= render '/layouts/guest_sub_header' %>
  <% end %>
  <hr width="50%" />
</div>

app/views/layouts/_new_sequence_form.html.erb
<div class="newSequence">
  <div class="newSequenceForm">
    <%= form_for(@sequence) do |f| %>
    <%= form_errors_for @sequence %>
      <div id="newSequenceTitle">
        <%= f.label :title %><br />
        <%= f.text_field :title %>
      </div>

      <div id="newSequenceDifficulty">
        <%= f.label :difficulty %>
        <h5 id="scale">1-5 scale, 1 = easiest, 5 = hardest </h5>
        <%= f.select :difficulty, options_for_select(1..5), :prompt => 'Select a level of difficulty' %>
      </div>

      <div class="pose_builder">
        <%= f.fields_for :poses do |pose_builder| %>
            <%= f.label :add_pose_to_this_sequence %>
            <%= select_tag 'sequence[pose_ids][]', options_from_collection_for_select(@poses.sort_by {|pose| pose.name}, "id", "name"), {:prompt => 'Select a pose'} %>
            or create a new pose:
            <%= pose_builder.label :name %>
            <%= pose_builder.text_field :name %>
            <%= pose_builder.label :description %>
            <%= pose_builder.text_field :description %><br />
        <% end %>
      </div>

      <br />

      <div class="repititions">
        <%= f.label :repititions %>
        <%= f.select :repititions, options_for_select(1..10), :prompt => 'Select number of repitions' %>
      </div>

      <br /><br />

      <%= f.submit %>
    <% end %>

  </div>

</div>

app/views/layouts/_pose_builder_form.html.erb
<div class="poseBuilder">
  <%= f.fields_for :poses do |pose_builder| %>
      <%= f.label :add_pose_to_this_sequence %>
      <%= select_tag 'sequence[pose_ids][]', options_from_collection_for_select(@poses, "id", "name"), { :prompt => 'Select a pose'} %>
      or create a new pose:
      <%= pose_builder.label :name %>
      <%= pose_builder.text_field :name %>
      <%= pose_builder.label :description %>
      <%= pose_builder.text_field :description %><br />
  <% end %>
</div>

app/views/layouts/_user.erb
<%= link_to "Log Out", log_out_path %>

app/views/layouts/_user_fields_form.html.erb
<div class="userForm">
  <% form_for @user do |f| %>
  <%= f.label :username %><br />
  <%= f.text_field :username %><br />
  <%= f.label :password %><br />
  <%= f.password_field :password %><br /><br />
  <%= f.submit %>
  <% end %>
</div>

app/views/layouts/_user_sub_header.erb
<div class="returnRoutes">
  <div class="linkText" id="goBack">
    <%= link_to "Go Back", root_path %>
  </div>
  <div class='linkText' id="logOut">
    <%= link_to "Log Out", log_out_path %>
  </div>
</div>

app/views/layouts/application.html.erb
<html>
  <head>
    <title>Yogaflow</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <div class="wrapper">
      <div class="header">
      <main>
        <%= render 'layouts/header' %>
        <%= yield :form_errors %>
        <%= yield %>
      </main>
      <div class="footer"></div>
    </div>
  </body>
  
</html>