config/routes.rb
Rails.application.routes.draw do
  root to: 'sequences#index'

  get 'sign_up', to: 'users#new', as: 'sign_up'
  get 'log_in', to: 'sessions#new', as: 'log_in'
  get 'log_out', to: 'sessions#destroy', as: 'log_out'
  get '/auth/github/callback' => 'sessions#create_with_github'
  post '/sequences/:id', to: 'sequences#update'
  patch '/sequences/:sequence_id/poses/:id', to: 'sequences#update'
  patch '/sequences/:sequence_id/poses', to: 'sequences#add_pose', as: 'sequence_add_pose'
  get '/sequences/:sequence_id/pose/:id', to: 'poses#list'

  resources :sequences do
    resources :poses, only: [:index, :new]
    resources :comments, only: [:create]
  end

  resources :users, only: [:create]
  resources :sessions, only: [:create]

end

app/models/sequence.rb
class Sequence < ActiveRecord::Base
  has_many :sequence_poses
  has_many :poses, through: :sequence_poses
  has_many :comments
  belongs_to :user
  validates :title, presence: true
  validates :title, uniqueness: true
  validates :difficulty, presence: true
  validates :repititions, presence: true
  before_save :repeated

  def self.most_poses
    most_poses = Sequence.maximum("number_of_poses")
    Sequence.where(:number_of_poses => most_poses)
  end

  def set_new_sequence_poses(params)
    set_poses(params)
    update_pose_array
    update_number_of_poses
    self.save
  end

  def set_poses(params)
    @sequence_array = []
    params.each do |attribute|
      if attribute[0] == "pose_ids"
        #sets poses added from pre-existing pose choices
        set_pose_ids(attribute[1])
      elsif attribute[0] == "poses_attributes"
        #sets poses created from scratch or typed in
        set_new_pose_ids(attribute[1])
      elsif attribute[0] == "pose" && attribute[1].values.first != "" && attribute[1].values.last != ""
        #adds new poses to the sequence after creation
        set_new_sequence_pose_ids(attribute[1])
      end
    end
    @sequence_array
  end

  def set_pose_ids(attribute)
    attribute.each_with_index do |pose_id, i|
      if pose_id != ""
        #adds pose if valid to the array at the index for the order it was created at
        @sequence_array[i] = Pose.find(pose_id)
      end
    end
  end

  def set_new_pose_ids(attribute)
    attribute.each.with_index do |pose, i|
      if pose[1].values[0] == "" || pose[1].values[1] == ""
      else
        @pose = Pose.find_or_create_by(name: pose[1].values[0])
        if @pose.description == nil
          @pose.description = pose[1].values[1]
          @pose.save
        end
        #adds pose if valid to the array at the index for the order it was created at
        @sequence_array[i] = @pose
      end
    end
  end

  def set_new_sequence_pose_ids(attribute)
    if attribute.values.first && attribute.values.last
      @pose = Pose.find_or_create_by(:name => attribute.values.first)
      if @pose.description == nil
        @pose.description = attribute.values.last
        @pose.save
      end
      #adds pose to the end of the sequence
      @sequence_array << @pose
    end
  end

  def poses_attributes=(poses_attributes)
    poses_attributes.each do |i, pose_attributes|
      if pose_attributes.values.first == "" || pose_attributes.values.last == ""
      else
        self.poses.build(pose_attributes)
      end
    end
  end

private

  #checks to see if pose is repeated within the sequence and updates the DB
  def repeated
    self.poses.each do |pose|
      pose_count = self.poses.where(:name => pose.name).count
      if pose_count > 1
        @pose = sequence_poses.find_by(:pose_id => pose.id)
        @pose.update(:repeated => true)
        @pose.save
      end
    end
  end

  def update_pose_array
    self.poses = @sequence_array
  end

  def update_number_of_poses
    self.number_of_poses = self.poses.count
  end

end

app/controllers/sequences_controller.rb
class SequencesController < ApplicationController
  before_action :set_poses

  def index
    @sequences = Sequence.all
    @users = User.all
  end

  def new
    if current_user
      @sequence = Sequence.new
      pose_builder
    else
      redirect_to log_in_path
    end
  end

  def create
    #creates a new sequence
    @sequence = Sequence.create(sequence_params)
    if @sequence.valid?
      #sets poses that make up the sequence
      @sequence.set_new_sequence_poses(params[:sequence])
      redirect_to sequences_path
    else
      #renders create new sequence form with errors
      flash[:error] = @sequence.errors
      pose_builder
      render :new
    end
  end

  def show
    set_sequence
    response = {
      :sequence => JSON.parse(@sequence.to_json(:include => [:poses])),
      :ids => Sequence.all.map { |sequence| sequence.id  },
      :comments => JSON.parse(@sequence.comments.to_json(:include => [:user => {:only => [:username]}]))
        }
    respond_to do |f|
      f.html { render :'/poses/index' }
      f.json { render json: response }
    end
  end

  def edit
    set_sequence
  end

  def update
    set_sequence
    @sequence.update(:repititions => sequence_params[:repititions])
    #updates sequence poses from edit poses form
    @sequence.poses = @sequence.set_poses(params[:sequence])
    redirect_to sequence_poses_path(@sequence)
  end

  def add_pose
    #updates sequence poses from add new pose form
    @sequence = Sequence.find(params[:sequence_id])
    @sequence.poses << @sequence.set_poses(params[:sequence])
    redirect_to sequence_poses_path(@sequence)
  end

  private

  def set_poses
    @poses = Pose.all
  end

  def pose_builder
    #builds pose fields for new/add pose forms
    15.times do
      @sequence.poses.build
    end
  end

  def set_sequence
    @sequence = Sequence.find(params[:id])
  end

  def sequence_params
    params.require(:sequence).permit(:title, :difficulty, :repititions, :pose_ids, poses_attributes: [:name, :description, :pose_ids])
  end

end

app/helpers/sequences_helper.rb
module SequencesHelper
  def longest_sequence
    Sequence.most_poses.first
  end

  def sequence_title
    @sequence.title.titleize
  end
end

app/views/sequences/edit.html.erb
<div class="editPage">
  <div id="sequenceTitle">
    <h1>Edit "<%= sequence_title %>"</h1>
  </div>
  <div id="editPoseForm">
    <%= render 'layouts/edit_sequence_poses' %>
  </div>
</div>

app/views/sequences/index.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.5/css/bootstrap.min.css" integrity="sha384-AysaV+vQoT3kOAXZkl02PThvDr8HYKPZhNT5h/CXfBThSRXQ6jW5DO2ekP5ViFdi" crossorigin="anonymous">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js" integrity="sha384-3ceskX3iaEnIogmQchP8opvBy3Mi7Ce34nWjpBIwVTHfGYWQS9jwHDVRnpKKHJg7" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.3.7/js/tether.min.js" integrity="sha384-XTs3FgkjiBgo8qjEjBk0tGmf3wPrWtA6coPfQDfFEY8AnYJwjalXCiosYRBIBZX8" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.5/js/bootstrap.min.js" integrity="sha384-BLiI7JTZm+JWlgKa0M0kGRpJbF2J8q+qreVrKBC47e3K6BW78kGLrCkeRX6I9RoK" crossorigin="anonymous"></script>
  </head>

  <body>
    <div id="sequenceHeader">
      <% if current_user %>
        <span><h1>Please select a yoga sequence: <h4><%= collection_select(:sequence, :sequence_id, @sequences, :id, :title, {:class => 'sequence_selection'}) %></h4>
        </h1></span>
      <!-- <% if longest_sequence %>
        <h3>The sequence with the most poses is "<%= longest_sequence.title %>"</h3>
      <% end %> -->
    </div>
    <!-- <div id="sequences">
      <div class="row">
        <% @sequences.each do |sequence| %>
          <div class="col-lg-4">
              <h3><h2><%= link_to sequence.title, sequence_path(sequence), class: 'linkText'  %></h2>
          </div>
        <% end %>
      </div>
    </div> -->
    <div class="navBar">
      <hr width="25%" />
      <h2 id="newSequence">
        <%= link_to "Create a new sequence", new_sequence_path, class: 'linkText'  %>
        <% end %>
      </h2>
      <%= render '/layouts/chakras' %>
    </div>
  </body>
</html>

app/views/sequences/new.html.erb
<div class="createSequence">
  <h1>Create a new yoga sequence</h1>
  <%= render 'layouts/new_sequence_form' %>
</div>

app/views/sequences/show.html.erb
<%= render "layouts/go_back" %>

<div class="description" align="center">
  <h1><%= @sequence.title %></h1>
  <ul style="list-style: none;">
    <li>Difficulty Rating: <%= @sequence.difficulty %></li>
  </ul>

  <h2> For <%= @sequence.repititions %> rounds, repeat the following sequence of poses:
    <% @sequence.poses.each.with_index do |pose, i| %>
      <h3><%= i + 1 %>. <%= pose.name %> - <%= pose.description %></h3>
    <% end %>
  </h2>
</div>